"""Migration-Message

Revision ID: 907072455152
Revises: 
Create Date: 2021-07-23 21:13:37.614688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '907072455152'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('cand_doc_cand_idx', table_name='candidate_documents')
    op.alter_column('documents', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=False)
    op.alter_column('documents', 'url',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=510),
               nullable=False)
    op.alter_column('domain_tasks', 'job_domain_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('domain_tasks', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=512),
               nullable=False)
    op.alter_column('domain_tasks', 'name_vn',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=512),
               nullable=False)
    op.alter_column('job_notes', 'note_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_index('note_cand_idx', table_name='job_notes')
    op.drop_index('note_jp_idx', table_name='job_notes')
    op.alter_column('skills', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=False)
    op.alter_column('subcribes', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('subcribes', 'type',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_index('sub_cand_idx', table_name='subcribes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('sub_cand_idx', 'subcribes', ['cand_id'], unique=False)
    op.alter_column('subcribes', 'type',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('subcribes', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('skills', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True)
    op.create_index('note_jp_idx', 'job_notes', ['job_post_id'], unique=False)
    op.create_index('note_cand_idx', 'job_notes', ['cand_id'], unique=False)
    op.alter_column('job_notes', 'note_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('domain_tasks', 'name_vn',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=512),
               nullable=True)
    op.alter_column('domain_tasks', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=512),
               nullable=True)
    op.alter_column('domain_tasks', 'job_domain_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('documents', 'url',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=510),
               nullable=True)
    op.alter_column('documents', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True)
    op.create_index('cand_doc_cand_idx', 'candidate_documents', ['cand_id'], unique=False)
    # ### end Alembic commands ###
